dist: trusty
language: c

before_install:
# pull git submodules
- git submodule update --init --recursive

# setup toolchains
- sudo apt-get update -qq
- sudo apt-get install -y gcc-arm-none-eabi
- sudo apt-get install -y gcc-avr binutils-avr avr-libc
- sudo apt-get install -y protobuf-compiler protobuf-c-compiler libprotobuf-dev

# upgrade pip and install python-protobuf package
- pip install --user -U pip
- pip install --user protobuf

script:
# stm32f0v1 board
- make ARCH=arm PLAT=stm32f0v1 deps
- make ARCH=arm PLAT=stm32f0v1 app
- make ARCH=arm PLAT=stm32f0v1 distclean

# attiny85v1 board
- make ARCH=avr PLAT=attiny85v1 deps
- make ARCH=avr PLAT=attiny85v1 app
- make ARCH=avr PLAT=attiny85v1 distclean

# devduino2 board
- make ARCH=avr PLAT=devduino2 deps
- make ARCH=avr PLAT=devduino2 app
- make ARCH=avr PLAT=devduino2 distclean

install: true
